swagger: '2.0'
info:
  title: "Mechanic Shop API"
  description: "This is documentation for a Mechanic Shop API customer tracking system."
  version: "1.0.0"
host: "127.0.0.1:5000"
schemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"
securityDefinitions:
  bearerAuth:
    type: "apiKey"
    name: "Authorization"
    in: "header"
paths:
  #* Mechanics Paths
  /mechanics/login:
    post:
      tags:
        - "Mechanics"
      summary: "Login a mechanic (generate a token)"
      description: "Post login credentials including email and password, and receive a token if successful"
      parameters:
        - in: body
          name: body
          description: "Login credentials for the mechanic"
          required: true
          schema: 
            type: object
            properties:
              email:
                type: string
              password:
                type: string
      responses:
        200:  # Changed from 201 to 200
          description: "Login successful"
          schema:
            type: object
            properties:
              token:
                type: string
          examples:
            application/json:
              token: "eyJhbGciOiJIUzI1NiIsI..."

  /mechanics:
    post:
      tags:
        - "Mechanics"
      summary: "Create a new mechanic"
      description: "Send JSON payload including mechanic details to create a new mechanic in database"
      parameters:
        - in: body
          name: body
          description: "Information of mechanic to be created"
          required: true
          schema: 
            $ref: "#/definitions/MechanicPayload" 
      responses:
        201:
          description: "Mechanic created successfully"
          schema:
            $ref: "#/definitions/MechanicResponse" 
          examples:  
            application/json:
              email: "test@test.com"
              id: 1
              name: "Test Testly"
              password: "pass"
              salary: 50000
              tickets: []

    get:
        tags:
          - "Mechanics"
        summary: "Get all mechanics"
        description: "Endpoint to return all mechanics"
        responses:
          200:
            description: "Successfully retrieved mechanics"
            schema:
              $ref: "#/definitions/MechanicListResponse"

  /mechanics/{mechanic_id}:
    get:
      tags:
        - "Mechanics"
      summary: "Get a mechanic by ID"
      parameters:
        - in: path
          name: mechanic_id
          type: integer
          required: true
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/MechanicResponse"

    put:
      tags:
        - "Mechanics"
      summary: "Update a mechanic (requires authentication)"
      description: "Update an existing mechanic's information requires mechanic to be logged in"
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: mechanic_id
          type: integer
          required: true
          description: "ID of the mechanic to update"
        - in: body
          name: body
          description: "Information used update a mechanic"
          required: true
          schema: 
            $ref: "#/definitions/MechanicPayload" 
      responses:
        200: 
          description: "Successful Update"
          schema:
            $ref: "#/definitions/MechanicResponse"

    delete:
      tags: 
        - "Mechanics"
      summary: "Delete a mechanic (requires authentication)"
      description: "Delete a mechanic from the database requires mechanic to be logged in"
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: mechanic_id
          type: integer
          required: true
      responses:
        200:
          description: "Mechanic deleted successfully"
    
  #* Customers paths
  /customers:
    post:
      tags:
        - "Customers"
      summary: "Create a new Customer"
      description: "Send JSON payload including customer details to create a new customer in database"
      parameters:
        - in: body
          name: body
          description: "Information of customer to be created"
          required: true
          schema: 
            $ref: "#/definitions/CustomerPayload" 
      responses:
        201:
          description: "Customer created successfully"
          schema:
            $ref: "#/definitions/CustomerResponse" 
          examples:  
            application/json:
              email: "test@testing.com"
              id: 1
              name: "Test Customer"
              phone: "123-456-7890"
              tickets: []
    get:
      tags:
          - "Customers"
      summary: "Get all customers"
      description: "Endpoint to return all customers"
      responses:
        200:
          description: "Successfully retrieved customers"
          schema:
            $ref: "#/definitions/CustomerListResponse"    
  /customers/{customer_id}:
    get:
      tags:
        - "Customers"
      summary: "Get a customer by ID"
      parameters:
        - in: path
          name: customer_id
          type: integer
          required: true
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/CustomerResponse"

    put:
      tags:
        - "Customers"
      summary: "Update a customer (requires authentication)"
      description: "Update an existing customer's information requires mechanic to be logged in"
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: customer_id
          type: integer
          required: true
          description: "ID of the customer to update"
        - in: body
          name: body
          description: "Information used update a customer"
          required: true
          schema: 
            $ref: "#/definitions/CustomerPayload" 
      responses:
        200:  
          description: "Successful Update"
          schema:
            $ref: "#/definitions/CustomerResponse"

    delete:
      tags: 
        - "Customers"
      summary: "Delete a customer (requires authentication)"
      description: "Delete a customer from the database requires mechanic to be logged in"
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: customer_id
          type: integer
          required: true
      responses:
        200:
          description: "Customer deleted successfully"

  #* Service Ticket paths
  /service-tickets:
    post:
      tags:
        - "Service Tickets"
      summary: "Create a new service_tickets"
      description: "Send JSON payload including service ticket details to create a new service_tickets in database"
      parameters:
        - in: body
          name: body
          description: "Information of service ticket to be created"
          required: true
          schema: 
            $ref: "#/definitions/ServiceTicketPayload" 
      responses:
        201:
          description: "Service Ticket created successfully"
          schema:
            $ref: "#/definitions/ServiceTicketResponse" 
          examples:  
            application/json:
              VIN: "1HGCM82633A123456"
              customer_id: 1
              id: 2
              service_date: "2023-10-01"
              service_desc: "Oil Change"

    get:
      tags:
        - "Service Tickets"
      summary: "Get all service tickets"
      description: "Endpoint to return all service tickets"
      responses:
        200:
          description: "Successfully retrieved service tickets"
          schema:
            $ref: "#/definitions/ServiceTicketListResponse"

  /service-tickets/{service_ticket_id}:
    get:
      tags:
        - "Service Tickets"
      summary: "Get a service ticket by ID"
      parameters:
        - in: path
          name: service_ticket_id
          type: integer
          required: true
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/ServiceTicketResponse"

    put:
      tags:
        - "Service Tickets"
      summary: "Update a service ticket (requires authentication)"
      description: "Update an existing service ticket's information requires service ticket to be logged in"
      security:  # Fixed typo (was "security: inf")
        - bearerAuth: []
      parameters:
        - in: path
          name: service_ticket_id  # Fixed parameter name (no space)
          type: integer
          required: true
          description: "ID of the service ticket to update"
        - in: body
          name: body
          description: "Information used update a service ticket"
          required: true
          schema: 
            $ref: "#/definitions/ServiceTicketPayload" 
      responses:
        200: 
          description: "Successful Update"
          schema:
            $ref: "#/definitions/ServiceTicketResponse"

    delete:
      tags: 
        - "Service Tickets"
      summary: "Delete a service ticket (requires authentication)"
      description: "Delete a service ticket from the database requires service ticket to be logged in"
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: service_ticket_id  # Fixed parameter name (no space)
          type: integer
          required: true
      responses:
        200:
          description: "Service ticket deleted successfully"

#* part descriptions paths
  /part-descriptions:
    post:
      tags:
        - "Part Descriptions"
      summary: "Create a new part description"
      description: "Send JSON payload including part pescription details to create a new part description in database"
      parameters:
        - in: body
          name: body
          description: "Information of part description to be created"
          required: true
          schema: 
            $ref: "#/definitions/PartDescriptionPayload" 
      responses:
        201:
          description: "Part Description created successfully"
          schema:
            $ref: "#/definitions/PartDescriptioinResponse" 
          examples:  
            application/json:
              brand: "test brand"
              id: 1
              part_name: "test part"
              price: 100.00
              serialized_parts: []

    get:
      tags:
          - "Part Descriptions"
      summary: "Get all parts"
      description: "Endpoint to return all part descriptions"
      responses:
        200:
          description: "Successfully retrieved all part descriptions"
          schema:
            $ref: "#/definitions/PartDescriptionListResponse"  

  /part-descriptions/{part_description_id}:
    get:
      tags:
        - "Part Descriptions"
      summary: "Get a Part description by ID"
      parameters:
        - in: path
          name: part_description_id
          type: integer
          required: true
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/PartDescriptionResponse"

    put:
      tags:
        - "Part Descriptions"
      summary: "Update a part description"
      description: "Update an existing Part description's information"
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: part_description_id
          type: integer
          required: true
          description: "ID of the Part description to update"
        - in: body
          name: body
          description: "Information used update a Part description"
          required: true
          schema: 
            $ref: "#/definitions/PartDescriptionPayload" 
      responses:
        200:  
          description: "Successful Update"
          schema:
            $ref: "#/definitions/PartDescriptionResponse"

    delete:
      tags: 
        - "Part Descriptions"
      summary: "Delete a Part description"
      description: "Delete a Part description from the database "
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: Part description_id
          type: integer
          required: true
      responses:
        200:
          description: "Part description deleted successfully"

  #* Serialized Parts paths
  /serialized-parts:
    post:
      tags:
        - "Serialized Parts"
      summary: "Create a new serialized part"
      description: "Send JSON payload including part pescription details to create a new serialized part in database"
      parameters:
        - in: body
          name: body
          description: "Information of serialized part to be created"
          required: true
          schema: 
            $ref: "#/definitions/SerializedPartPayload" 
      responses:
        201:
          description: "Part Description created successfully"
          schema:
            $ref: "#/definitions/SerializedPartResponse" 
          examples:  
            application/json:
              brand: "test brand"
              desc_id: 1
              id: 1
              ticket_id: 1

    get:
      tags:
          - "Serialized Parts"
      summary: "Get all parts"
      description: "Endpoint to return all serialized parts"
      responses:
        200:
          description: "Successfully retrieved all serialized parts"
          schema:
            $ref: "#/definitions/SerializedPartListResponse"  

  /serialized-parts/{serialized_part_id}:
    get:
      tags:
        - "Serialized Parts"
      summary: "Get a Part by ID"
      parameters:
        - in: path
          name: serialized_part_id
          type: integer
          required: true
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/SerializedPartResponse"

    put:
      tags:
        - "Serialized Parts"
      summary: "Update a part"
      description: "Update an existing Parts information"
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: serialized_part_id
          type: integer
          required: true
          description: "ID of the Part to update"
        - in: body
          name: body
          description: "Information used update a Part"
          required: true
          schema: 
            $ref: "#/definitions/SerializedPartPayload" 
      responses:
        200:  
          description: "Successful Update"
          schema:
            $ref: "#/definitions/SerializedPartResponse"

    delete:
      tags: 
        - "Serialized Parts"
      summary: "Delete a Part"
      description: "Delete a Part  from the database "
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: serialized_part_id
          type: integer
          required: true
      responses:
        200:
          description: "Part deleted successfully"


    
              
definitions:
  #* Mechanics definitions
  MechanicPayload:
    type: object
    properties:
      name:
        type: string
      email:
        type: string
      password:
        type: string
      salary:
        type: integer

  MechanicResponse:
    type: object
    properties:
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      password:
        type: string
      salary:
        type: integer
      tickets:  
        type: array
        items:
          type: integer

  MechanicListResponse:
    type: array
    items:
      type: object
      properties:
        email:
          type: string
        id:
          type: integer
        name:
          type: string
        password:
          type: string
        salary:
          type: integer
        tickets:  
          type: array
          items:
            type: integer

  #* Customers definitions
  CustomerPayload:
    type: object
    properties:
      email:
        type: string
      name:
        type: string
      phone:
        type: string

  CustomerResponse:
    type: object
    properties:
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      phone:
        type: string
      tickets:
        type: array
        items:
          type: integer

  CustomerListResponse:
    type: array
    items:
      type: object
      properties:
        email:
          type: string
        id:
          type: integer
        name:
          type: string
        phone:
          type: string
        tickets:  
          type: array
          items:
            type: integer

  #* Service Ticket definitions
  ServiceTicketPayload:
    type: object
    properties:
      service_date:
        type: string
      VIN:
        type: string
      service_desc:
        type: string
      customer_id:
        type: integer

  ServiceTicketResponse:
    type: object
    properties:
      VIN:
        type: string
      customer_id:
        type: integer
      id:
        type: integer
      service_date:
        type: string
      service_desc:
        type: string

  ServiceTicketListResponse:
    type: array
    items:
      $ref: "#/definitions/ServiceTicketResponse" 

  #* Part Description definitions
  PartDescriptionPayload:
    type: object
    properties:
      brand:
        type: string
      part_name:
        type: string
      price:
        type: number
        format: float

  PartDescriptionResponse:
    type: object
    properties:
      brand:
        type: string
      id:
        type: integer
      part_name:
        type: string
      price:
        type: number
        format: float
      serialized_parts:
        type: array
        items:
          type: integer

  PartDescriptionListResponse:
    type: array
    items:
      $ref: "#/definitions/PartDescriptionResponse" 

  #* Serialized Part definitions
  SerializedPartPayload:
    type: object
    properties:
      desc_id:
        type: integer

  SerializedPartResponse:
    type: object
    properties:
      desc_id:
        type: integer
      id:
        type: integer
      ticket_id:
        type: integer

  SerializedPartListResponse:
    type: array
    items:
      $ref: "#/definitions/SerializedPartResponse" 