name: Flask CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Must be v4

      - name: Set up Python
        uses: actions/setup-python@v4 # Must be v4
        with:
          python-version: 3.12

      - name: Install Python venv module
        run: sudo apt-get install python3.12-venv -y

      - name: Create virtual environment
        run: |
          python3.12 -m venv venv || { echo "Failed to create venv"; exit 1; }
          ls -l venv || { echo "venv directory does not exist"; exit 1; }
          source venv/bin/activate

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Use pip directly

      - name: Verify environment
        run: |
          echo "Python path: $(which python)"
          echo "Pip path: $(which pip)"
          ls -l venv/bin
          ls -l venv/lib/python3.12/site-packages

  test:
    runs-on: ubuntu-latest
    needs: build # Add dependency on build job

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Python venv module
        run: sudo apt-get install python3.12-venv -y

      - name: Create virtual environment
        run: |
          python3.12 -m venv venv  # Use explicit python version
          source venv/bin/activate

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          source venv/bin/activate
          python -m unittest discover -s tests -p "tests_*.py"
