name: Flask CI/CD

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # Fix: Install required system package for venv
      - name: Install Python venv module
        run: sudo apt-get install python3.12-venv -y

      - name: Create virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify Python paths
        run: |
          echo "Python path: $(which python)"
          echo "Pip path: $(which pip)"
          ls -l venv/bin/python*

      - name: Run tests
        run: |
          source venv/bin/activate
          python -m unittest discover -s tests -p "tests_*.py"
