name: Flask CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Create virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Print debugging Info
        run: |
          echo "python version: $(python --version)"
          echo "working directory: $(pwd)"
          echo "contents of working directory: $(ls -l)"
          echo "contents of site-packages: $(ls -l venv/lib/python*/site-packages)"

  test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # Fix: Install required system package for venv
      - name: Install Python venv module
        run: sudo apt-get install python3.12-venv -y

      - name: Create virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify Python paths
        run: |
          echo "Python path: $(which python)"
          echo "Pip path: $(which pip)"
          ls -l venv/bin/python*

      - name: Run tests
        run: |
          source venv/bin/activate
        python -m unittest discover -s tests -p "tests_*.py"

